version: '3.8'

services:
  kea-bi-hml:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "6001:6001"
    env_file:
      - ../.env.hml
    environment:
      - ENVIRONMENT=homologation
      - SERVER_PORT=6001
      - DEBUG=False
    restart: unless-stopped
    container_name: kea-bi-homologation