version: '3.8'

services:
  kea-bi-prod:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "6000:6000"
    env_file:
      - ../.env.prod
    environment:
      - ENVIRONMENT=production
      - SERVER_PORT=6000
      - DEBUG=False
    restart: unless-stopped
    container_name: kea-bi-production